sudo: required

services:
  - docker

before_install:
  - docker build -t juuzeff/frontend-hello -f ./Lab5/frontend-hello/Dockerfile.dev ./Lab5/frontend-hello/.

script:
  - docker run -e CI=true juuzeff/frontend-hello yarn test
