apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc-new

spec:
  accessModes:
  - ReadWriteOnce # (ReadWriteOnce | ReadWriteMany | ReadOnlyMany)

  resources:
    requests:
      storage: 100Mi
