apiVersion: apps/v1

kind: Deployment

metadata:
  name: postgres-backend-deployment
  labels:
    app: postgres-backend
    type: backend

spec:
  template:
    metadata:
      name: postgres-backend-pod
      labels:
        app: postgres-backend
        type: backend
    spec:
      containers:
        - name: postgres-backend-container
          image: juuzeff/postgres-backend
  replicas: 3
  selector:
    matchLabels:
      app: postgres-backend
      type: backend
