apiVersion: v1

kind: Service

metadata:
  name: postgres-backend-nodeport

spec:
  type: NodePort
  ports:
    - targetPort: 5000 # port docelowy aplikacji w node
      port: 5000
      nodePort: 30009
  selector: # wybieramy deployment zgodny z yml [nazwy!]
    app: postgres-backend
    type: backend
